User.destroy_all
Business.destroy_all
Checkin.destroy_all
Wishlist.destroy_all

User.create(name: Faker::Name.name, username: Faker::Internet.username, password: Faker::Internet.password) 
User.create(name: Faker::Name.name, username: Faker::Internet.username, password: Faker::Internet.password)
User.create(name: Faker::Name.name, username: Faker::Internet.username, password: Faker::Internet.password)
User.create(name: Faker::Name.name, username: Faker::Internet.username, password: Faker::Internet.password)
User.create(name: Faker::Name.name, username: Faker::Internet.username, password: Faker::Internet.password)
User.create(name: Faker::Name.name, username: Faker::Internet.username, password: Faker::Internet.password)
User.create(name: Faker::Name.name, username: Faker::Internet.username, password: Faker::Internet.password)
User.create(name: Faker::Name.name, username: Faker::Internet.username, password: Faker::Internet.password)
User.create(name: Faker::Name.name, username: Faker::Internet.username, password: Faker::Internet.password)
User.create(name: Faker::Name.name, username: Faker::Internet.username, password: Faker::Internet.password)

Business.create(name: Faker::Company.name)
Business.create(name: Faker::Company.name)
Business.create(name: Faker::Company.name)
Business.create(name: Faker::Company.name)
Business.create(name: Faker::Company.name)
Business.create(name: Faker::Company.name)
Business.create(name: Faker::Company.name)
Business.create(name: Faker::Company.name)
Business.create(name: Faker::Company.name)
Business.create(name: Faker::Company.name)

Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Checkin.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)

Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
Wishlist.create(user_id: User.all.sample.id, business_id: Business.all.sample.id)
